apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app: mysqldb
spec:
  clusterIP: None
  selector:
    app: mysqldb
  ports:
    - name: tcp
      protocol: TCP
      port: 3306